version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tarunbatta"
    assignees:
      - "tarunbatta"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
    ignore:
      # Ignore major version updates for now (can be reviewed manually)
      - dependency-name: "Newtonsoft.Json"
        update-types: ["version-update:semver-major"]
